# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('community', models.CharField(max_length=25)),
                ('area_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ward', models.CharField(max_length=25)),
                ('ward_number', models.IntegerField()),
            ],
        ),
    ]
